// frontend/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { AuthService } from '../../services/auth.service';


@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  loginForm: FormGroup | any;
  errorMsg = '';

  constructor(private _auth: AuthService, private _router: Router, private fb: FormBuilder) { }

  ngOnInit(): void {
    this.loginForm = this.fb.group({
      username: ['', Validators.required],
      password: ['', Validators.required]
    })
  }

  get username(){
    return this.loginForm.get('username');
  }

  get password(){
    return this.loginForm.get('password');
  }

  loginUser(){
    this._auth.loginUser(this.loginForm.value).subscribe(
      res => {
        this.errorMsg = '';

        localStorage.setItem('access_token', res.access_token);
        this._router.navigate(['/dashboard']);
      },
      err => {
        this.errorMsg = err.error.message;
      }
    );
  }
}

<div class="py-5">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <span class="anchor" id="formLogin"></span>
          <div class="card rounded-0">
          <div class="card-header">
            <h3 class="mb-0">Login</h3>
          </div>
          <div class="card-body">
            <ngb-alert *ngIf="errorMsg" [type]="'danger'" (close)="errorMsg=''">{{ errorMsg }}</ngb-alert>
            <form class="form" [formGroup]="loginForm" (ngSubmit)="loginUser()" novalidate>
              <div class="form-group">
                <label for="">Username</label>
                <input type="text" formControlName="username"
                [class.is-invalid]="username.invalid && username.touched" 
                class="form-control rounded-0">
                <small class="text-danger" [class.d-none]="username.valid || username.untouched">Username is required</small>
              </div>
              <div class="form-group">
                <label>Password</label>
                <input type="password" formControlName="password"
                [class.is-invalid]="password.invalid && password.touched"
                class="form-control rounded-0">
                <small class="text-danger" [class.d-none]="password.valid || password.untouched">Password is required</small>
              </div>
              <button [disabled]="!loginForm.valid" type="submit" class="btn btn-success float-right">Login</button>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>

// frontend/src/pages/login.vue
<template>
  <div class="py-5">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card rounded-0">
          <div class="card-header">
            <h3 class="mb-0">Login</h3>
          </div>
          <div class="card-body">
            <div v-if="errorMsg" class="alert alert-danger" role="alert">
              {{ errorMsg }}
              <button type="button" class="close" @click="errorMsg = ''">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form @submit.prevent="loginUser" novalidate>
              <div class="form-group">
                <label for="username">Username</label>
                <input v-model="username" type="text" id="username" class="form-control rounded-0"
                  :class="{ 'is-invalid': !isUsernameValid && isUsernameTouched }">
                <small v-if="!isUsernameValid && isUsernameTouched" class="text-danger">Username is required</small>
              </div>
              <div class="form-group">
                <label for="password">Password</label>
                <input v-model="password" type="password" id="password" class="form-control rounded-0"
                  :class="{ 'is-invalid': !isPasswordValid && isPasswordTouched }">
                <small v-if="!isPasswordValid && isPasswordTouched" class="text-danger">Password is required</small>
              </div>
              <button :disabled="!isLoginFormValid" type="submit" class="btn btn-success float-right">Login</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import authService from '@/services/auth.service';

export default {
  name: 'UserLogin',
  data() {
    return {
      username: '',
      password: '',
      isUsernameTouched: false,
      isPasswordTouched: false,
      errorMsg: ''
    };
  },
  computed: {
    isUsernameValid() {
      return !!this.username.trim();
    },
    isPasswordValid() {
      return !!this.password.trim();
    },
    isLoginFormValid() {
      return this.isUsernameValid && this.isPasswordValid;
    }
  },
  methods: {
    async loginUser() {
      try {
        const res = await authService.loginUser({
          username: this.username,
          password: this.password
        });
        this.errorMsg = '';
        localStorage.setItem('access_token', res.access_token);
        this.$router.push('/dashboard');
      } catch (error) {
        console.error('Error logging in:', error);
        this.errorMsg = error.message || 'An error occurred during login.';
      }
    }
  }
};
</script>

<style scoped>
/* Add your component styles here */
</style>
